manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: osleg
      url-base: https://github.com/osleg/zmk.git
  projects:
    - name: zmk
      remote: osleg
      revision: encoders
      import: app/west.yml
  self:
    path: config
